### ISSUE TITLE
Is it possible to detect system settings for light/dark mode switch?

### ISSUE THREAD

**Issue by tvardero** [gumbarros/swagger-dark-theme#1]
_Related: https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript_

**Comment by tvardero** [comment]
Hmmm prob i could try to implement it myself
Wait for a PR in some future

**Comment by gumbarros** [comment]
Hey @tvardero , sorry, I think this not possible because this is just a static file generated by [Dark Reader](https://darkreader.org/).

Probably will need something like this:

```js
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
    // Do some logic to don't user dark-swagger.css
});
```

Maybe you can add to your website the [Dark Reader library](https://github.com/darkreader/darkreader), maybe they have some way to switch themes.

**Comment by tvardero** [comment]
Resolved with https://github.com/Amoenus/SwaggerDark/

It uses `@media (prefers-color-scheme: dark)`
